{
 "title": "Disk & IO",
 "description": "by MateusSouzaWeb",
 "tags": [
  "mateussouzaweb",
  "disk",
  "io"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1s,5s,10s,15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "host",
    "query": "SHOW TAG VALUES FROM \"system\" WITH KEY = \"host\""
   },
   {
    "name": "disk",
    "label": "disk",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"device\" WHERE \"host\" =~ /$host/"
   },
   {
    "name": "iodevice",
    "label": "iodevice",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH key = \"name\" WHERE \"host\" =~ /^$host$/ AND \"name\" =~ /^([sh]d[a-z]+|md[0-9]+|dm(-)?[0-9]+)([0-9]+)?$/"
   }
  ]
 },
 "panels": [
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk used",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$tag_device - $tag_path",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT max(used_percent) FROM \"disk\" WHERE \"host\" =~ /^$host$/ and \"device\" != 'rootfs'  and $timeFilter",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_device - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"value\") FROM \"disk_total\" WHERE $timeFilter GROUP BY time($interval), \"tag\", \"tag\"",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk inodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_device - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$interval" ], "type": "time" },
      { "key": "host", "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"inodes_used\") AS \"used\" FROM \"disk\" WHERE $timeFilter GROUP BY time($interval), \"device\"",
     "select": [
      [
       { "params": [ "inodes_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "$tag_device - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$interval" ], "type": "time" },
      { "key": "host", "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(inodes_free) + mean(inodes_used) as \"total\" FROM \"disk\" WHERE \"host\" =~ /$host$/  AND \"device\" =~ /^$disk$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "inodes_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "$tag_device - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$interval" ], "type": "time" },
      { "key": "host", "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(inodes_free) + mean(inodes_used) as \"total\" FROM \"disk\" WHERE \"host\" =~ /$host$/  AND \"device\" =~ /^$disk$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "inodes_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk I/O requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$interval" ], "type": "time" },
      { "key": "host", "params": [ "name" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "query": "SELECT mean(\"value\") FROM \"io_reads\" WHERE $timeFilter GROUP BY time($interval), \"tag\", \"tag\"",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "$tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$interval" ], "type": "time" },
      { "key": "host", "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(writes),1s) AS \"write\" FROM \"diskio\" WHERE \"host\" =~ /$host$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$interval" ], "type": "time" },
      { "key": "host", "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(\"write_bytes\"), 1s) AS \"write\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/ AND \"name\" =~ /^$disk$/) AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "$tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$interval" ], "type": "time" },
      { "key": "host", "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(\"read_bytes\"), 1s) AS \"read\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/ AND \"name\" =~ /^$disk$/) AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$interval" ], "type": "time" },
      { "key": "host", "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(\"read_bytes\"), 1s) AS \"read\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/ AND \"name\" =~ /^$disk$/) AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       { "params": [ "read_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "$tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$interval" ], "type": "time" },
      { "key": "host", "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(\"read_bytes\"), 1s) AS \"read\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/ AND \"name\" =~ /^$disk$/) AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       { "params": [ "write_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  }
 ]
}