{
 "title": "InfluxDB Internal Basics",
 "description": "InfluxDB Bare Bones Basics internal data explorer.\r\n\r\n + Lists Databases\r\n + Lists Measurements\r\n + Lists Retention policies\r\n + Lists Series\r\n + Lists Field Keys\r\n + Lists Tag Keys\r\n + Lists Tag Values\r\n",
 "tags": [
  "influxdb",
  "internal",
  "metrics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" },
   { "name": "database", "label": "Database", "query": "show databases" },
   {
    "name": "measurement",
    "label": "Measurement",
    "query": "SHOW MEASUREMENTS on \"$database\""
   },
   {
    "name": "tag_key",
    "label": "Tag Key",
    "query": "SHOW TAG KEYS ON \"$database\" from \"$measurement\""
   }
  ]
 },
 "panels": [
  {
   "title": "General Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Databases",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SHOW DATABASES",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Measurements",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SHOW MEASUREMENTS ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Retention policies",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SHOW RETENTION POLICIES",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Measurement Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Tag Keys",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG KEYS ON \"$database\" FROM \"$measurement\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tag Values",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 7, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES ON \"$database\"  FROM \"$measurement\" WITH KEY = \"$tag_key\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Field Keys",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW FIELD KEYS ON \"$database\" FROM \"$measurement\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Series",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW SERIES ON \"$database\"  FROM \"$measurement\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}