{
 "title": "System Alerts",
 "description": "by MateusSouzaWeb",
 "tags": [
  "mateussouzaweb",
  "alerts",
  "system",
  "host"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Last Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 } },
  { "title": "OK Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 } },
  {
   "title": "CPU usage > 80%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "cpu - $tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage > 90%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk usage > 80%",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_device",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "fstype", "operator": "=", "value": "ext4" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O write bytes > 70mb",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_name",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "1m" ], "type": "time" },
      { "key": "host", "params": [ "name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(\"write_bytes\"), 1s) AS \"write\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/ AND \"name\" =~ /^$disk$/) AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O read bytes > 70mb",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host -  $tag_name",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "1m" ], "type": "time" },
      { "key": "host", "params": [ "name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(\"read_bytes\"), 1s) AS \"read\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/ AND \"name\" =~ /^$disk$/) AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "read" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O write time > 200ms",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_name",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "1m" ], "type": "time" },
      { "key": "host", "params": [ "name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(\"read_bytes\"), 1s) AS \"read\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/ AND \"name\" =~ /^$disk$/) AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       { "params": [ "write_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O read time > 200ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_name",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "1m" ], "type": "time" },
      { "key": "host", "params": [ "name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(\"read_bytes\"), 1s) AS \"read\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/ AND \"name\" =~ /^$disk$/) AND $timeFilter GROUP BY time($interval), \"name\"",
     "select": [
      [
       { "params": [ "read_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "read" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth inbound > 70mb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_interface",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "1m" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(\"bytes_recv\"), 1s) *8 AS \"in\" FROM \"net\" WHERE (\"host\" =~ /^$host$/ AND \"interface\" =~ /^$interface$/) AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "in" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth outbound > 70mb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_interface",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "1m" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"out\" FROM \"net\" WHERE (\"host\" =~ /^$host$/ AND \"interface\" =~ /^$interface$/) AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "out" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}