{
 "title": "Traefik",
 "description": "by MateusSouzaWeb",
 "tags": [
  "mateussouzaweb",
  "traefik"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1s,5s,10s,15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "query": "SHOW TAG VALUES FROM \"traefik.entrypoint.requests.total\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_service - $tag_method - $tag_code",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "code" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traefik.service.requests.total",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_service - $tag_method - $tag_code",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "code" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traefik.service.request.duration",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections Open",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_service - $tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traefik.service.connections.open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Entrypoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_entrypoint - $tag_method - $tag_code",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "entrypoint" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "code" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traefik.entrypoint.request.duration",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_entrypoint - $tag_method - $tag_code",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "entrypoint" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "code" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traefik.entrypoint.requests.total",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections Open",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_entrypoint - $tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "entrypoint" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traefik.entrypoint.connections.open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}